### ISSUE TITLE
Wider Perl versions support

### ISSUE THREAD

**Issue by eyadof** [binary-com/perl-Myriad#146]
In the memory transport we are using a Perl 5.32+ specific syntax [ `isa`](https://github.com/binary-com/perl-Myriad/blob/master/lib/Myriad/RPC/Implementation/Memory.pm#L70)

this is not essential and it's the only place that we require such feature, better to replace it with a more compatible approach.

**Comment by tom-binary** [comment]
As part of this, we should update the minimum requirement to 5.028, since that's the last time the signature/attribute ordering was flipped.

https://perldoc.perl.org/perl5280delta#Subroutine-attribute-and-signature-order
