### ISSUE TITLE
Redis transport: Cleanup empty groups on shutdown

### ISSUE THREAD

**Issue by eyadof** [binary-com/perl-Myriad#186]
Redis will be filled with empty unused groups, to avoid that we should delete the group on shutdown.

The groups are: 
- RPC groups
- Subscriptions groups

The process should consider other consumers who are still active and using the group, so it should check the idle time for the consumers in that group.

An arbitrary assumption is that the consumers will be active every [`15000 ms`](https://github.com/binary-com/perl-Myriad/blob/master/lib/Myriad/Transport/Redis.pm#L57).

A better alternative is to make the service deletes its consumers from Redis then check the group info for deletion.

A cleanup script should be also available through Myriad's CLI.

**Comment by tom-binary** [comment]
A group isn't necessarily empty - service ordering means we could be populating a group long before there's anything ready to read from it, and if we stop/restart that producer it shouldn't drop the group.

Some form of cleanup does make sense, but would need much longer timeframes - likely to be weeks, not seconds, and would also vary depending on installation and use-cases.

I'll close this for now, although the cleanup script does make sense: we're likely to add that as part of the upcoming UI work.
